import io
import os
import logging
from datetime import datetime
from django.conf import settings
from django.utils import timezone
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image
)
from reportlab.lib import colors

from .models import Report
from apps.monitoring.models import Website
from apps.alerts.models import Incident, Alert
from apps.analysis.models import AnalysisResult

logger = logging.getLogger(__name__)


class PDFReportGenerator:
    """Service for generating PDF reports using ReportLab."""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()

    def _add_custom_styles(self):
        """Add custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            textColor=HexColor('#1a1a2e'),
            spaceAfter=30,
        ))
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading1'],
            fontSize=16,
            textColor=HexColor('#16213e'),
            spaceBefore=20,
            spaceAfter=10,
        ))
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=HexColor('#333333'),
        ))

    def generate_report(self, report: Report) -> str:
        """
        Generate a PDF report.
        
        Args:
            report: The Report model instance
            
        Returns:
            Path to the generated PDF file
        """
        report.status = 'generating'
        report.save()
        
        try:
            # Create buffer
            buffer = io.BytesIO()
            
            # Create document
            doc = SimpleDocTemplate(
                buffer,
                pagesize=A4,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=72,
            )
            
            # Build content
            story = self._build_report_content(report)
            
            # Generate PDF
            doc.build(story)
            
            # Save to file
            filename = f"report_{report.id}_{timezone.now().strftime('%Y%m%d_%H%M%S')}.pdf"
            filepath = os.path.join(settings.MEDIA_ROOT, 'reports', filename)
            
            # Ensure directory exists
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            
            # Write file
            with open(filepath, 'wb') as f:
                f.write(buffer.getvalue())
            
            # Update report
            report.file = f'reports/{filename}'
            report.file_size = os.path.getsize(filepath)
            report.status = 'completed'
            report.generated_at = timezone.now()
            report.save()
            
            logger.info(f"Generated report: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Failed to generate report: {str(e)}")
            report.status = 'failed'
            report.save()
            raise

    def _build_report_content(self, report: Report) -> list:
        """Build the report content elements."""
        story = []
        
        # Title
        story.append(Paragraph("Deface Spy", self.styles['CustomTitle']))
        story.append(Paragraph(report.title, self.styles['CustomHeading']))
        story.append(Spacer(1, 20))
        
        # Report Info
        info_data = [
            ['Report Type:', report.get_report_type_display()],
            ['Generated:', timezone.now().strftime('%Y-%m-%d %H:%M:%S UTC')],
            ['Generated By:', report.user.email],
        ]
        if report.start_date:
            info_data.append(['Period Start:', str(report.start_date)])
        if report.end_date:
            info_data.append(['Period End:', str(report.end_date)])
        
        info_table = Table(info_data, colWidths=[2*inch, 4*inch])
        info_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.grey),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 30))
        
        # Summary section
        story.append(Paragraph("Summary", self.styles['CustomHeading']))
        story.extend(self._build_summary_section(report))
        story.append(Spacer(1, 20))
        
        # Incidents section
        story.append(Paragraph("Incidents", self.styles['CustomHeading']))
        story.extend(self._build_incidents_section(report))
        story.append(Spacer(1, 20))
        
        # Alerts section
        story.append(Paragraph("Alerts", self.styles['CustomHeading']))
        story.extend(self._build_alerts_section(report))
        
        return story

    def _build_summary_section(self, report: Report) -> list:
        """Build summary section of the report."""
        elements = []
        user = report.user
        
        # Only include active (live) websites in the report
        active_websites = Website.objects.filter(user=user, status='active')
        total_websites = active_websites.count()
        total_incidents = Incident.objects.filter(website__user=user, website__status='active').count()
        total_alerts = Alert.objects.filter(website__user=user, website__status='active').count()
        active_alerts = Alert.objects.filter(
            website__user=user,
            website__status='active',
            status='active'
        ).count()
        
        # Create summary table
        summary_data = [
            ['Metric', 'Value'],
            ['Total Websites', str(total_websites)],
            ['Total Incidents', str(total_incidents)],
            ['Total Alerts', str(total_alerts)],
            ['Active Alerts', str(active_alerts)],
        ]
        
        table = Table(summary_data, colWidths=[3*inch, 2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWHEIGHTS', (0, 0), (-1, -1), 25),
        ]))
        
        elements.append(table)
        
        # Store data in report
        report.data = {
            'total_websites': total_websites,
            'total_incidents': total_incidents,
            'total_alerts': total_alerts,
            'active_alerts': active_alerts,
        }
        report.save()
        
        return elements

    def _build_incidents_section(self, report: Report) -> list:
        """Build incidents section of the report."""
        elements = []
        user = report.user
        
        # Get recent incidents from active websites only
        incidents = Incident.objects.filter(
            website__user=user,
            website__status='active'
        ).order_by('-created_at')[:10]
        
        if not incidents:
            elements.append(Paragraph(
                "No incidents recorded.",
                self.styles['CustomBody']
            ))
            return elements
        
        # Create incidents table
        incident_data = [['Website', 'Severity', 'Status', 'Date']]
        for inc in incidents:
            incident_data.append([
                inc.website.name[:20],
                inc.severity.upper(),
                inc.status,
                inc.created_at.strftime('%Y-%m-%d'),
            ])
        
        table = Table(incident_data, colWidths=[2*inch, 1.2*inch, 1.2*inch, 1.2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor('#e94560')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWHEIGHTS', (0, 0), (-1, -1), 20),
        ]))
        
        elements.append(table)
        return elements

    def _build_alerts_section(self, report: Report) -> list:
        """Build alerts section of the report."""
        elements = []
        user = report.user
        
        # Get recent alerts from active websites only
        alerts = Alert.objects.filter(
            website__user=user,
            website__status='active'
        ).order_by('-created_at')[:10]
        
        if not alerts:
            elements.append(Paragraph(
                "No alerts recorded.",
                self.styles['CustomBody']
            ))
            return elements
        
        # Create alerts table
        alert_data = [['Website', 'Title', 'Severity', 'Status']]
        for alert in alerts:
            alert_data.append([
                alert.website.name[:15],
                alert.title[:25],
                alert.severity.upper(),
                alert.status,
            ])
        
        table = Table(alert_data, colWidths=[1.5*inch, 2.5*inch, 1*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor('#0f3460')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWHEIGHTS', (0, 0), (-1, -1), 20),
        ]))
        
        elements.append(table)
        return elements
