# Generated by Django 5.2.11 on 2026-02-13 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_data', models.JSONField(default=dict, help_text='8x8 matrix comparison data')),
                ('changed_blocks', models.IntegerField(default=0)),
                ('total_blocks', models.IntegerField(default=64)),
                ('change_percentage', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score (0-100)')),
                ('similarity_score', models.FloatField(default=100.0, help_text='Similarity score (0-100)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('is_defacement_detected', models.BooleanField(default=False)),
                ('ai_explanation', models.TextField(blank=True, help_text='AI-generated explanation of changes')),
                ('visual_changes', models.JSONField(default=list, help_text='List of detected visual changes')),
                ('content_changes', models.JSONField(default=list, help_text='List of detected content changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compared_analyses', to='monitoring.snapshot')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='monitoring.snapshot')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
