# Generated by Django 5.2.11 on 2026-02-13 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_monitoring_interval', models.IntegerField(default=60, help_text='Default monitoring interval in minutes')),
                ('max_snapshots_per_website', models.IntegerField(default=100, help_text='Maximum snapshots to keep per website')),
                ('auto_delete_old_snapshots', models.BooleanField(default=True)),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('alert_on_high_severity', models.BooleanField(default=True)),
                ('alert_on_critical_severity', models.BooleanField(default=True)),
                ('defacement_threshold', models.FloatField(default=10.0, help_text='Change percentage threshold for defacement detection')),
                ('min_confidence_score', models.FloatField(default=80.0, help_text='Minimum confidence score for valid analysis')),
                ('scheduler_enabled', models.BooleanField(default=True)),
                ('scheduler_interval_minutes', models.IntegerField(default=5)),
                ('incident_retention_days', models.IntegerField(default=90)),
                ('report_retention_days', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('notify_on_high', models.BooleanField(default=True)),
                ('notify_on_critical', models.BooleanField(default=True)),
                ('notify_on_medium', models.BooleanField(default=False)),
                ('notify_on_low', models.BooleanField(default=False)),
                ('dashboard_refresh_interval', models.IntegerField(default=30, help_text='Dashboard auto-refresh interval in seconds')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('default_report_type', models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed'), ('incident', 'Incident')], default='summary', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
