import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Website, Alert } from '@/data/mockData';

interface ReportData {
  website: Website;
  alerts: Alert[];
  analysisResults: {
    changedBlocks: number;
    totalBlocks: number;
    confidence: number;
    severity: string;
    textChanges: number;
  };
  generatedAt: Date;
}

export function generatePDFReport(data: ReportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const primaryColor: [number, number, number] = [16, 185, 129]; // Emerald green
  const textColor: [number, number, number] = [226, 232, 240];
  const mutedColor: [number, number, number] = [148, 163, 184];
  const bgColor: [number, number, number] = [15, 23, 42];

  // Dark background
  doc.setFillColor(...bgColor);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(22);
  doc.setFont('courier', 'bold');
  doc.text('DEFACE SPY', 20, 25);

  doc.setFontSize(9);
  doc.setFont('courier', 'normal');
  doc.text('DEFACEMENT DETECTION REPORT', 20, 33);

  // Report Info
  doc.setFillColor(30, 41, 59);
  doc.rect(15, 50, pageWidth - 30, 30, 'F');

  doc.setTextColor(...textColor);
  doc.setFontSize(11);
  doc.setFont('courier', 'bold');
  doc.text('INCIDENT ANALYSIS REPORT', 20, 62);

  doc.setFontSize(9);
  doc.setFont('courier', 'normal');
  doc.setTextColor(...mutedColor);
  doc.text(`Generated: ${data.generatedAt.toLocaleString()}`, 20, 72);

  // Website Details
  let yPos = 95;
  doc.setTextColor(...primaryColor);
  doc.setFontSize(12);
  doc.setFont('courier', 'bold');
  doc.text('TARGET DETAILS', 20, yPos);

  yPos += 12;
  const websiteDetails = [
    ['Target Name', data.website.name],
    ['URL', data.website.url],
    ['Status', data.website.status.toUpperCase()],
    ['Baseline Date', new Date(data.website.baselineDate).toLocaleDateString()],
    ['Last Scanned', new Date(data.website.lastChecked).toLocaleDateString()],
    ['Scan Interval', `${data.website.monitoringInterval} minutes`],
    ['Frames Analyzed', data.website.framesAnalyzed.toLocaleString()],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [],
    body: websiteDetails,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 3, textColor: textColor, font: 'courier' },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50, textColor: mutedColor } },
    margin: { left: 20 },
  });

  // Analysis
  yPos = (doc as any).lastAutoTable.finalY + 15;
  doc.setTextColor(...primaryColor);
  doc.setFontSize(12);
  doc.setFont('courier', 'bold');
  doc.text('ANALYSIS RESULTS', 20, yPos);

  yPos += 12;
  autoTable(doc, {
    startY: yPos,
    head: [],
    body: [
      ['Confidence', `${data.analysisResults.confidence}%`],
      ['Severity', data.analysisResults.severity.toUpperCase()],
      ['Changed Blocks', `${data.analysisResults.changedBlocks} / ${data.analysisResults.totalBlocks}`],
      ['Visual Change', `${((data.analysisResults.changedBlocks / data.analysisResults.totalBlocks) * 100).toFixed(1)}%`],
      ['Text Modifications', data.analysisResults.textChanges.toString()],
    ],
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 3, textColor: textColor, font: 'courier' },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50, textColor: mutedColor } },
    margin: { left: 20 },
  });

  // Alerts
  if (data.alerts.length > 0) {
    yPos = (doc as any).lastAutoTable.finalY + 15;
    if (yPos > pageHeight - 80) { doc.addPage(); doc.setFillColor(...bgColor); doc.rect(0, 0, pageWidth, pageHeight, 'F'); yPos = 20; }

    doc.setTextColor(...primaryColor);
    doc.setFontSize(12);
    doc.setFont('courier', 'bold');
    doc.text('ALERT HISTORY', 20, yPos);

    yPos += 10;
    autoTable(doc, {
      startY: yPos,
      head: [['Type', 'Severity', 'Confidence', 'Date', 'Status']],
      body: data.alerts.map(a => [a.type.replace('_', ' ').toUpperCase(), a.severity.toUpperCase(), `${a.confidence}%`, new Date(a.timestamp).toLocaleDateString(), a.resolved ? 'Resolved' : 'Active']),
      theme: 'striped',
      headStyles: { fillColor: primaryColor, textColor: [15, 23, 42], fontStyle: 'bold', font: 'courier' },
      styles: { fontSize: 8, cellPadding: 3, textColor: textColor, font: 'courier' },
      alternateRowStyles: { fillColor: [30, 41, 59] },
      margin: { left: 20, right: 20 },
    });
  }

  // Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(7);
  doc.setTextColor(...mutedColor);
  doc.text('Generated by Deface Spy • Web Defacement Detection System', pageWidth / 2, footerY, { align: 'center' });

  doc.save(`DefaceSpy_Report_${data.website.name.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
}

export function generateSummaryReport(
  websites: Website[],
  alerts: Alert[],
  stats: { totalWebsites: number; framesAnalyzed: number; defacementsDetected: number; safeWebsites: number }
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const primaryColor: [number, number, number] = [16, 185, 129];
  const textColor: [number, number, number] = [226, 232, 240];
  const mutedColor: [number, number, number] = [148, 163, 184];
  const bgColor: [number, number, number] = [15, 23, 42];

  doc.setFillColor(...bgColor);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(22);
  doc.setFont('courier', 'bold');
  doc.text('DEFACE SPY', 20, 25);
  doc.setFontSize(9);
  doc.setFont('courier', 'normal');
  doc.text('EXECUTIVE SUMMARY', 20, 33);
  doc.text(new Date().toLocaleDateString(), pageWidth - 20, 25, { align: 'right' });

  let yPos = 55;
  doc.setTextColor(...primaryColor);
  doc.setFontSize(12);
  doc.setFont('courier', 'bold');
  doc.text('OVERVIEW', 20, yPos);

  yPos += 15;
  const cardWidth = (pageWidth - 50) / 4;
  [
    { label: 'Targets', value: stats.totalWebsites.toString() },
    { label: 'Frames', value: stats.framesAnalyzed.toLocaleString() },
    { label: 'Threats', value: stats.defacementsDetected.toString() },
    { label: 'Secure', value: stats.safeWebsites.toString() },
  ].forEach((stat, index) => {
    const x = 20 + (index * cardWidth) + (index * 5);
    doc.setFillColor(30, 41, 59);
    doc.rect(x, yPos, cardWidth, 28, 'F');
    doc.setTextColor(...textColor);
    doc.setFontSize(16);
    doc.setFont('courier', 'bold');
    doc.text(stat.value, x + cardWidth / 2, yPos + 14, { align: 'center' });
    doc.setFontSize(7);
    doc.setTextColor(...mutedColor);
    doc.setFont('courier', 'normal');
    doc.text(stat.label.toUpperCase(), x + cardWidth / 2, yPos + 22, { align: 'center' });
  });

  yPos += 45;
  doc.setTextColor(...primaryColor);
  doc.setFontSize(12);
  doc.setFont('courier', 'bold');
  doc.text('MONITORED TARGETS', 20, yPos);
  yPos += 10;

  autoTable(doc, {
    startY: yPos,
    head: [['Name', 'URL', 'Status', 'Frames', 'Last Scan']],
    body: websites.map(w => [w.name, w.url, w.status.toUpperCase(), w.framesAnalyzed.toLocaleString(), new Date(w.lastChecked).toLocaleDateString()]),
    theme: 'striped',
    headStyles: { fillColor: primaryColor, textColor: [15, 23, 42], fontStyle: 'bold', font: 'courier' },
    styles: { fontSize: 8, cellPadding: 3, textColor: textColor, font: 'courier' },
    alternateRowStyles: { fillColor: [30, 41, 59] },
    columnStyles: { 1: { cellWidth: 50 } },
    margin: { left: 20, right: 20 },
  });

  const footerY = pageHeight - 15;
  doc.setFontSize(7);
  doc.setTextColor(...mutedColor);
  doc.text(`Generated by Deface Spy • ${new Date().toLocaleString()}`, pageWidth / 2, footerY, { align: 'center' });

  doc.save(`DefaceSpy_Summary_${Date.now()}.pdf`);
}
