# Generated by Django 5.2.11 on 2026-02-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Security Analyst')], default='admin', max_length=50),
        ),
    ]
